### ISSUE TITLE
导入完应用名称变成LFilePickerActivity

### ISSUE THREAD

**Issue by idis573** [leonHua/LFilePicker#10]

**Comment by LiuYiAC** [comment]
在Manifest文件中APP下面加属性        tools:replace="android:label"
然后再把android:label="@string/app_name1"换成其他的就行了
但是不方面  建议作者修改一下

**Comment by leonHua** [comment]
@LiuYiAC 我目前就是用你说的这种方式解决的，请问还有其它更好的方式吗？

**Comment by neilzhengzx** [comment]
主项目参照LFilePicker在res中添加value-zh
