### ISSUE TITLE
MultiDex (Multiple dex files define) Error

### ISSUE THREAD

**Issue by Mehran-Abghari** [leonHua/LFilePicker#16]
Hello, I'm using AndroidUtilCode seperatly in my project and also using MultiDex option. When add your library in my project, Then i got 'MultiDex: Multiple dex files define Lcom/Blankj/utilcode/util/LogUtils' !

**Comment by leonHua** [comment]
Hello,I also applied to AndroidUtilCode in my library, but I just quoted a few of them,do not include
LogUtils

**Comment by Mehran-Abghari** [comment]
Hello, I delete .gradle folder and rebuild my project, It fixes problem. Thanks
