### ISSUE TITLE
可以选择文件夹吗？

### ISSUE THREAD

**Issue by xuelongqy** [leonHua/LFilePicker#17]
需要一个选择文件夹的功能

**Comment by leonHua** [comment]
选择文件夹是指？选择到某个文件夹下的路径地址，具体的逻辑场景是什么呢？

**Comment by xuelongqy** [comment]
比如要下载一个文件，然后选择保存文件夹

**Comment by leonHua** [comment]
可以，这个会列入待开发清单，不过完成时间不能保证哦，会尽快谢谢支持~~~

**Comment by xuelongqy** [comment]
好的，谢谢哦。我在MaterialFilePicker的基础上，添加了选择文件夹模式。有时间我会推送上来，如果需要的话，我把地址给你

**Comment by leonHua** [comment]
好的，欢迎提 Pull ，我回头看看

**Comment by leonHua** [comment]
@xuelongqy 文件夹选择已经添加，更新版本，使用看readme，有介绍。使用发现问题欢迎继续反馈~~~

**Comment by xuelongqy** [comment]
好的，谢谢。辛苦了
