### ISSUE TITLE
为什么 返回上一级 会出现 暂无数据？

### ISSUE THREAD

**Issue by as11051105** [leonHua/LFilePicker#2]
为什么 返回上一级 会出现 暂无数据？

**Comment by leonHua** [comment]
返回上一级是类似storage/emulated这样的吧，我查看了系统底部linux系统下这个文件夹没有读写权限，所以无法获取数据。参考了熊猫读书、书旗小说、多多小说中的文件读取，这块也都是没有数据。
或者就是处理storage/emulated/0这个就是根目录，不允许用于再向上选择，基本上用户选择文件也就是在这个目录下
