### ISSUE TITLE
状态栏颜色要么暴露出来给用户设定，要么用系统默认颜色，不然会很丑

### ISSUE THREAD

**Issue by PeterGoower** [leonHua/LFilePicker#20]
如题

状态栏就是系统显示电量信号那玩意，现在状态栏和我设定的标题栏颜色不一样，太违和了

**Comment by leonHua** [comment]
在你的应用中配置colorPrimaryDark来改变标题栏颜色，我测试了下是可以改变的。

**Comment by PeterGoower** [comment]
是不行的，我用的是沉浸式的状态栏，也就是状态栏颜色是和状态栏下UI颜色保持一致的。但因为你的Activity我无法改动，无法继承我自己的BaseActivity。  
实在不行我只能下载你的源码包含到工程里然后改你代码，不去gradle引用了。

总之谢了，除了这个，这个库还是很好用的

**Comment by leonHua** [comment]
状态栏颜色默认是随着你项目主体中的颜色来的（colorPrimaryDark），你只需要调用        .withBackgroundColor("#303F9F")这个属性方法，把标题栏颜色改变，就一致了

**Comment by PeterGoower** [comment]
您的这种方式并不通用，因为每个项目状态栏都有不同是实现。
事实上我调用withBackgroundColor，但只能改变标题栏，状态栏还是

    Constant.ICON_STYLE_YELLOW
    Constant.ICON_STYLE_BLUE
    Constant.ICON_STYLE_GREEN
这三种主题之一。



我们项目用了沉浸式状态栏，其实现的代码如下（写这么多是为了适配不同的安卓版本）

package com.sstcsoft.hs.util;

import android.annotation.TargetApi;
import android.app.Activity;
import android.content.Context;
import android.os.Build.VERSION;
import android.os.Build.VERSION_CODES;
import android.view.View;
import android.view.ViewGroup;
import android.view.WindowManager;

import com.sstcsoft.hs.R;

/***
 * 状态栏透明 工具类
 * @author jery
 *
 */
public class StatusBarCompat {
	private static final int INVALID_VAL = -1;
//    private static final int COLOR_DEFAULT = Color.parseColor("#25B6ED"); //默认颜色

    @TargetApi(VERSION_CODES.LOLLIPOP)
    public static void compat(Activity activity, int statusColor) {
		int colorDefault = activity.getResources().getColor(R.color.theme_color_default); // 默认颜色
		if (VERSION.SDK_INT == VERSION_CODES.KITKAT) {
			// 透明状态栏
			activity.getWindow().addFlags(
					WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS);
			// 透明导航栏
			activity.getWindow().addFlags(
					WindowManager.LayoutParams.FLAG_TRANSLUCENT_NAVIGATION);
		}

		if (VERSION.SDK_INT >= VERSION_CODES.LOLLIPOP) {
			int v= VERSION.SDK_INT;
				activity.getWindow().setStatusBarColor(colorDefault);
			
			return;
		}

		if (VERSION.SDK_INT >= VERSION_CODES.KITKAT
				&& VERSION.SDK_INT < VERSION_CODES.LOLLIPOP) {
			int color = colorDefault;
			ViewGroup contentView = (ViewGroup) activity
					.findViewById(android.R.id.content);
			if (statusColor != INVALID_VAL) {
				color = statusColor;
			}
			View statusBarView = contentView.getChildAt(0);
			// 改变颜色时避免重复添加statusBarView
			if (statusBarView != null
					&& statusBarView.getMeasuredHeight() == getStatusBarHeight(activity)) {
				statusBarView.setBackgroundColor(color);
				return;
			}
			statusBarView = new View(activity);
			ViewGroup.LayoutParams lp = new ViewGroup.LayoutParams(
					ViewGroup.LayoutParams.MATCH_PARENT,
					getStatusBarHeight(activity));
			statusBarView.setBackgroundColor(color);
			contentView.addView(statusBarView, lp);
		}

	}
    
    
    public static void compat(Activity activity)
    {
        compat(activity, INVALID_VAL);
    }


    public static int getStatusBarHeight(Context context)
    {
        int result = 0;
        int resourceId = context.getResources().getIdentifier("status_bar_height", "dimen", "android");
        if (resourceId > 0)
        {
            result = context.getResources().getDimensionPixelSize(resourceId);
        }
        return result;
    }
}

**Comment by michaellct** [comment]
状态栏颜色默认是随着你项目主体中的颜色来的（colorPrimaryDark） 这是不对的
 因为你代码使用的是defaultColor   所以我们只能在我们的colors中 `<color name="defaultColor">@color/colorPrimary</color>` 重写才可以

**Comment by michaellct** [comment]
````
    <color name="colorAccent">#92B4F4</color>
    <color name="colorPrimary">#92B4F4</color>
    <color name="colorPrimaryDark">#92B4F4</color>
    <color name="defaultColor">#92B4F4</color>
````
 ```
<android.support.v7.widget.Toolbar
        android:id="@+id/toolbar"
        android:layout_width="match_parent"
        android:layout_height="?android:attr/actionBarSize"
        android:theme="@style/ToolbarTheme"
        android:background="@color/defaultColor"
        app:titleTextColor="@color/white"
        app:title="txt">
```
