### ISSUE TITLE
引入LFilePicker后，应用名字被修改为LFilePicker...

### ISSUE THREAD

**Issue by kbxwn** [leonHua/LFilePicker#24]
如题，即使在项目的AndroidManifest.xml文件下，在<application>节点添加tools:replace="android:label"，app运行起来后，app的名字还是为LFilePicker...，初步查找发现是这个库AndroidManifest.xml文件下<application>节点也添加了tools:replace="android:label"，导致gradle合并清单文件有冲突，暂未找到可行的解决办法

**Comment by leonHua** [comment]
https://github.com/leonHua/LFilePicker/issues/10
