### ISSUE TITLE
app应用名称被修改

### ISSUE THREAD

**Issue by 283958849** [leonHua/LFilePicker#26]
为什么使用你的这个库后，app的名称都被修改了，有什么办法改回我自己的吗？谢谢！

**Comment by leonHua** [comment]
看看这个：https://github.com/leonHua/LFilePicker/issues/10
或者看我的demo里的配置

**Comment by 283958849** [comment]
已解决，修改的地方我列出来如下，方便后来者：

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"  //这个会自动添加
    package="com.gree.transferfiles">

    <application
        android:allowBackup="true"
        tools:replace="android:label"   //1，添加这个
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_new_name"  //2，这里用新的变量名称，并,在string.xml中添加对应的值
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity
            android:name=".MainActivity"
            android:label="@string/app_name">   //这一行需要删除，否则还是被改
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
