### ISSUE TITLE
应用名覆盖问题

### ISSUE THREAD

**Issue by tsubasa-kun** [leonHua/LFilePicker#28]
你好，我在导入这个库之后，原来的应用名就会被你这个库的应用名覆盖，请问有什么解决办法吗？

**Comment by leonHua** [comment]
https://github.com/leonHua/LFilePicker/issues/26

**Comment by leonHua** [comment]
https://github.com/leonHua/LFilePicker/issues/26 这里有解决方法

**Comment by tsubasa-kun** [comment]
好的
