### ISSUE TITLE
为啥不改下app_name???

### ISSUE THREAD

**Issue by bhui** [leonHua/LFilePicker#29]
每个人遇到了都一脸懵逼，引入一个第三库连应用名称都被改了，这???

**Comment by pengjiazhen** [comment]
库里面有zh/values-zh文件，如果你应用里面没有，直接读库里面的app_name

**Comment by Ordosbxy** [comment]
建议作者库里边不要使用app_name， 加个前缀 lfile_picker_app_name

**Comment by lxj-helloworld** [comment]
过分了

**Comment by lxj-helloworld** [comment]
第一次留言，给你了，竟然改了APP名字，

**Comment by leonHua** [comment]
说明：如果发现应用名称被修改，可以参考issues#26 查看解决方案，或者可以自己下载代码依赖改动，目前木有精力改动，如果你改了欢迎提pull，如果不能接受此缺陷，请慎用~
