### ISSUE TITLE
大神，可以考虑添加隐藏文件夹只显示文件功能吗

### ISSUE THREAD

**Issue by ejwdhr** [leonHua/LFilePicker#5]

**Comment by leonHua** [comment]
我不是大神哈~你这个是什么意思？是想不显示隐藏文件夹吗？

**Comment by leonHua** [comment]
我不是大神哈~你这个是什么意思？是想不显示隐藏文件夹吗？ @ejwdhr

**Comment by ejwdhr** [comment]
@leonHua 就是比如我想要.jpg的文件列表就只显示.jpg的文件不显示文件夹还需要一层一层的点开文件夹去找.jpg

**Comment by leonHua** [comment]
@ejwdhr 这种方式就是循环递归过滤出文件后放到一个列表中显示了，本身应该没什么难度，考虑下效率的问题就可以了。最近在忙别的项目，这个暂时不加。如果你实现了，欢迎提pull共享哈~~
