### ISSUE TITLE
Constant or Consant, both cannot work Correctly?

### ISSUE THREAD

**Issue by zyw745293** [leonHua/LFilePicker#6]
Constant.REQUESTCODE_FROM_ACTIVITY
Constant.RESULT_INFO

These are CANNOT be resolved, why?

**Comment by leonHua** [comment]
@zyw745293 Sorry,This is a mistake in my article,Constant.REQUESTCODE_FROM_ACTIVITY is in my sample project,you can define your own.
Constant.RESULT_INFO is in the pageage of com.leon.lfilepickerlibrary.utils,you can replace it with “”paths“”.
Thank you for correcting me. If you have any questions, please contact me again. If these solve your problems, please let me know.
